env: "dev" # Available options: dev, staging, production

app:
  name: "botvideosaver"

telegramBot:
  token: "<your-telegram-bot-token>"
  proxy: # Optional proxy settings
    type: "socks5" # Available options: socks5, mtproxy
    address: ""
    port: 1080
    username: "" # Optional, for authenticated proxies
    password: "" # Optional, for authenticated proxies

postgres:
  url: "" # "postgresql://doadmin:... Neither url nor host/port/database/username/password is set
  host: "" # use "host.docker.internal" if you run app inside docker container
  port: "5432"
  database: ""
  username: ""
  password: ""
  maxConnections: 8
  maxIdleConnections: 10
  logQuery: false

browserpool:
  poolSize: 10 # Number of browser instances to run concurrently
  proxies: [] # List of proxy URLs to use for browser instances, equals or less than poolSize (protocol://username:password@host:port)
  taskQueueSize: 5 # Maximum number of tasks each browser instance can handle concurrently

log:
  level: "debug" # debug, info, warn, error, dpanic, panic, fatal
  stacktraceLevel: "error"
  fileEnabled: true
  fileSize: 10 # MB
  filePath: "log/log.log"
  fileCompress: false # enable log file compress before rotate
  maxAge: 1 # days to keep log files
  maxBackups: 10 # number of log files
